services: 
    # Path controller
    innova_favorite.controller.sidebar:
        class: %innova_favorite.controller.sidebar.class%
        arguments:
            favoriteManager: @innova_favorite.manager.favorite
